# action.yml
name: 'GitHub Slug'
description: 'Action to slug and expose some github variables'
inputs:
  short_sha_length:
    description: 'Length of the SHORT_SHA variable'
    required: true
    default: '8'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'crop'
  color: 'orange'
